export default {
  colors: {
    blueViolet: ['#4596EA', '#7145CB'],
    gradientBg: ['#F9F8FD', '#FFFFFF'],
    primary: '#157EFB',
    danger: '#FC595B',
    white: '#FFFFFF',
    lightGray: '#F8F7FB',
    lightGray2: '#F0F0F8',
    orange: '#F1A852',
    violet: '#4552CB',
    darkBlue: '#2E1E7A',
    black: '#000000',
    yellow: '#FFCF6F',
    gray: '#BBC3CE',
    palegray: '#F9FAFB',

    text_title: '#404040',
    text_subTitle: '#B3B3B3',
    text_paragraph: '#808080',
    text_caption: '#B3B3B3',
    text_placeholder: '#B3B3B3',
    text_danger: '#FC595B',
    text_contrast: '#FFFFFF',

    background: '#FFFFFF',
    background_neutral_1: '#F5F5F5',
    background_neutral_2: '#E8E8E8',

    shadow: '#404040',
  },
  effects: {
    roundIconShadow: {
      shadowColor: 'rgb(46, 30, 122)',
      shadowOpacity: 0.08,
      shadowOffset: {width: 3, height: 3},
      shadowRadius: 34,
    },
    outlinePlahaShadow: {
      shadowColor: '#271D4B',
      shadowOpacity: 0.03,
      shadowOffset: {width: 3, height: 3},
      shadowRadius: 5,
    },
    plahaShadow: {
      shadowColor: '#2D368A',
      shadowOpacity: 0.08,
      shadowOffset: {width: 4, height: 6},
      shadowRadius: 28,
      elevation: 5,
    },
    blueShadow: {
      shadowColor: 'rgba(46, 30, 122, 0.2)',
      shadowOpacity: 1,
      shadowOffset: {width: 1, height: 1},
      shadowRadius: 1,
      elevation: 1,
    },
  },
  fonts: {
    bold: 'EncodeSans-Bold',
    semiBold: 'EncodeSans-SemiBold',
    medium: 'EncodeSans-Medium',
    regular: 'EncodeSans-Regular',
  },
};
